SELECT
    CASE
        WHEN G.GRADE >= 8 THEN S.NAME
        ELSE 'NULL'
    END,
    G.GRADE, S.MARKS
FROM STUDENTS AS S
LEFT JOIN GRADES AS G
ON S.MARKS BETWEEN MIN_MARK AND MAX_MARK
ORDER BY
    GRADE DESC,
    NAME ASC;
